# Generated by Django 5.2.6 on 2025-11-06 22:36

import django.db.models.deletion
import trainmydog.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'ชาย'), ('female', 'หญิง'), ('other', 'อื่น ๆ'), ('prefer_not', 'ไม่ระบุ')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email_snapshot', models.EmailField(blank=True, help_text='อีเมล ณ เวลายื่นคำร้อง', max_length=254)),
                ('intro', models.TextField(help_text='แนะนำตัว/ประสบการณ์/เพิ่มเติมที่อยากเขียน')),
                ('portfolio_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('approved', 'อนุมัติ'), ('rejected', 'ปฏิเสธ')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_apps_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainerCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=trainmydog.models.certificate_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='trainmydog.trainerapplication')),
            ],
        ),
    ]
